spring.main.banner-mode=off
###### App Identification  ########
app.env=APPD
app.group=L1
app.name=MS-JOB
app.id=J1s

server.port=8050
app.swagger=true
app.monitor=false
app.cache=false
app.audit=true

server.servlet.contextPath=/bot
server.contextPath=/bot

logging.level.org.springframework.web=ERROR
logging.level.org.hibernate=ERROR
logging.level.org.springframework=ERROR
logging.level.org.apache=ERROR
logging.level.com.amx.jax=INFO

spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

spring.data.elasticsearch.cluster-name=elasticsearch
spring.data.elasticsearch.cluster-nodes=10.28.42.21:9200
elasticsearch.clustername=bootloader
elasticsearch.scheme=http
elasticsearch.host=10.28.42.21
elasticsearch.port=9200
elasticsearch.username=dev
elasticsearch.password=D#V@2019@A@M#X
elasticsearch.url=${elasticsearch.scheme}://${elasticsearch.host}:${elasticsearch.port}
elasticsearch.enabled=true
#elasticsearch.timezone=Asia/Calcutta
elasticsearch.timezone=Asia/Riyadh

jax.postman.url=https://pmd1-kwt.amxremit.com

spring.redis.host=localhost
spring.redis.port=6379


##### OracleDB ############
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@10.28.42.10:1521:TAGDMS
spring.datasource.username=agdmslink
spring.datasource.password=agdmslink
#spring.datasource.url=jdbc:oracle:thin:@192.170.161.99:1521:QEMOS
#spring.datasource.username=QJOAMX_USER
#spring.datasource.password=QJOAMX#456

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
spring.jpa.properties.hibernate.cache.use_second_level_cache=false
spring.jpa.properties.hibernate.cache.region.factory_class=org.hibernate.cache.ehcache.EhCacheRegionFactory
#spring.jpa.properties.hibernate.cache.use_second_level_cache=true
#spring.jpa.properties.hibernate.cache.region.factory_class=org.hibernate.cache.ehcache.EhCacheRegionFactory
#spring.jpa.properties.hibernate.jdbc.batch_size=1000

########## Fle Size limit  ########################
multipart.max-file-size=20MB
multipart.max-request-size=50MB
spring.http.multipart.max-file-size=20MB
spring.http.multipart.max-request-size=50MB
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=50MB

jax.jobs.dms.migrate=true

## JACKSON
spring.jackson.deserialization.fail-on-unknown-properties=false


app.test.email=
app.test.mobile=
app.test.whatsapp=




