postman.service.url=http://127.0.0.1:8082/postman
postman.agent.url=
postman.bot.url=
postman.contact.details.url=
postman.chat.session.timeout=24hr
postman.chat.idle.timeout=5min
postman.chat.client.key=RANDOM
postman.default.sender=postman
postman.bot.name=

postman.agent.session.timeout=10min
postman.agent.chat.init=false
postman.agent.scheme.color=#4b56c0

app.local.dummy.bot.enabled=false

app.test.email=
app.test.mobile=
app.test.whatsapp=

postman.nlp.enabled=false
postman.nlp.opennlp.enabled=false
postman.nlp.corenlp.enabled=false
postman.nlp.optimaize.enabled=true

postman.dms.api.key=816e96f868641cf0c266a6b2b753f07c
postman.dms.api.secret=8639852979ac4381b548a277ed001c56
postman.dms.api.server=${postman.service.url}
postman.dms.api.callback=
